misc: Upgrade workflows versions, add support for 3.11 and trigger tweaks (#2)
* misc: Upgrade workflows versions add support for 3.11

* fixup: cleanup workflow dir and use correct test

* fixup: drop python 3.6 due to architecture issues in 22.04

> Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
Python 3.6 is not available in Ubuntu 22.04, which would force us to
reduce the OS requirement.

Ref: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

* workflows: revert test run

* workflows: tweak workflow triggers

* fixup: missing test triggers

Signed-off-by: Gustavo Silva <gustavosantaremsilva@gmail.com>

---------

Signed-off-by: Gustavo Silva <gustavosantaremsilva@gmail.com>