fixup: drop python 3.6 due to architecture issues in 22.04
> Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
Python 3.6 is not available in Ubuntu 22.04, which would force us to
reduce the OS requirement.

Ref: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json